# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='audo_file',
            new_name='audio_file',
        ),
    ]
